### ISSUE TITLE
Environment Variables

### ISSUE THREAD

**Issue by rlmd-fonseca** [hasherezade/process_doppelganging#2]
I found by creating a program that printed all the Environment Variables that process doppelganging wasn't setting any Environment Variables.

![1567085035299](https://user-images.githubusercontent.com/54672768/64325140-847d0600-cfbf-11e9-9fee-27b6dc5b3857.png)

So I tried to set Environment variables through the parameter environment on the function RtlCreateProcessParametersEx()

![1567086433402](https://user-images.githubusercontent.com/54672768/64325188-9c548a00-cfbf-11e9-9542-3251d7e23e2a.png)

Which lead to the exact same results as if I had passed a nullptr.

I then created a simple program just to test the normal creation of a process through CreateProcess()

The conclusions I got from it were:

1. CreateProcess() will take either an ANSI string and later on convert it into UNICODE and pass it to RtlCreateProcessParametersEx() or an UNICODE string and the flag CREATE_UNICODE_ENVIRONMENT and skip the conversion and then pass it to RtlCreateProcessParametersEx(). In either case the first API called was CreateProcessInternalW()
2. CreateProcessW() requires every string to be in UNICODE and calls CreateProcessInternalW() and passing a UNICODE string with the Environment Variables to RtlCreateProcessParametersEx()
3. CreateProcessA() requires every string to be ANSI, then it converts them to UNICODE and proceeds to call CreateProcessInternalW() and passing a UNICODE string with the Environment Variables to RtlCreateProcessParametersEx()

The UNICODE string with the Environment variables can be seen here:
![1567091243818](https://user-images.githubusercontent.com/54672768/64325209-a6768880-cfbf-11e9-9bf2-f3cf921ca9c4.png)

With this concluded and examining the the RtlCreateProcessParametersEx() dynamically when running process doppelganging it's possible to see that it was being passed a pointer to a UNICODE string with the environment variables.

![1567091302360](https://user-images.githubusercontent.com/54672768/64325222-abd3d300-cfbf-11e9-965d-2611b3575f95.png)

The issue here being on how to then correctly set the Environment Variables

**Comment by hasherezade** [comment]
Thank you for submitting! Please let me know if this patch helps.

**Comment by rlmd-fonseca** [comment]
The environment variables now set properly.
